### ISSUE TITLE
CustomerType entity is not correct

### ISSUE THREAD

**Issue by AndreasOngoing** [FortnoxAB/csharp-api-sdk#101]
Hi

Currently the CustomerType enum contains two values, Private and Company. This matches the  [documentation](https://developer.fortnox.se/documentation/resources/customers/). However, in our Fortnox I have encountered several customers where the customer type is literally "UNDEFINED". This can't be parsed into the enum and causes an exception. These customers cannot be fetched using the SDK.

This is what the JSON reply from Fortnox's API looks like:

![image](https://user-images.githubusercontent.com/57254947/89180473-21f70600-d592-11ea-8c3b-5974e3c14667.png)

**Comment by richardrandak** [comment]
Thanks for reporting the issue. I will add the value to the SDK.

**Comment by richardrandak** [comment]
Seems like it is impossible to create a customer with "UNDEFINED" type. This may result in problem that you can retried a customer, but Update will fail due to the illegal value. Nevertheless, i will add the value marked as obsolete.
