### ISSUE TITLE
How to set a field an a entity to null or empty via the C# API

### ISSUE THREAD

**Issue by ThomasBjallas** [FortnoxAB/csharp-api-sdk#102]
It would be great if the C# API would make it possible to clear the values in a field on a entity.

In my use case I would like to remove the value in Invoice.Phone1 after the invoice was created. But setting the Phone1 filed to NULL or a empty string will be handled as "Not changed" and therefore it will not be updated when updating the invoice.

It would be nice if the API allowed me to mark the Phone1 field as "Dirty" so that it will be saved even if the new value is null or a empty string.

This applies to all fields, not only Invoice.Phone1 that I was working on right now.

**Comment by bpaolo71** [comment]
https://developer.fortnox.se/general/general/#Delete-values

**Comment by ThomasBjallas** [comment]
Perfect

Thanks!
