### ISSUE TITLE
Move Find from specific connector interface to IEntityConnector

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#103]
If i understood correctly interface IEntityConnection define all fields need in the Find function but not the Find itself.
Shouldn't be better to change IEntityConnection in this way:
```
public interface IEntityConnector<T> : IConnector
    {
        //Base search params
        int? Limit { get; set; }
        DateTime? LastModified { get; set; }
        int? Page { get; set; }
        int? Offset { get; set; }
        EntityCollection<T> Find();
    } 
```
and specific inteface in that way:
`public interface IArticleConnector : IEntityConnector<ArticleSubset>
	{
...`

**Comment by richardrandak** [comment]
The problem is that not all connectors have Find method, maybe an interface should be added like "ISearch" defined as you suggest and implemented just by those connectors which offers Find() method.

**Comment by bpaolo71** [comment]
Should't all properties in IEntityConnector (Limit, LastModified, Page etc) used with Find method ? right ?
So if a connector doesn't implement Find it shouldn't have IEntityConnector interface too ?

**Comment by richardrandak** [comment]
Yeah, that is right.
