### ISSUE TITLE
Not able to search on Project name anymore

### ISSUE THREAD

**Issue by jezloop** [FortnoxAB/csharp-api-sdk#108]
Hi

I updated my version to get the newest version but I am missing the ability to search for Projects by name which I used in the old version:
projectConnector.Description = projectName;
projects = projectConnector.Find();

Best regards

**Comment by richardrandak** [comment]
Well, I guess you were using very old version. I generated/rewritten code based on [documentation](https://developer.fortnox.se/documentation/resources/projects/). As you can see here, the description is not searchable for projects. <img width="539" alt="Screenshot_72" src="https://user-images.githubusercontent.com/58220739/94784223-268f3d80-03ce-11eb-8f74-58799c2a0e86.png"> I can check if the search works and ask around if its just a mistake in the documentation. If yes, the property will be added to SDK.

**Comment by jezloop** [comment]
Hi

Yes, quite old but the same major version: 3.0.0.0 :)
I still using the old one so should work but maybe not the same endpoints.

Best regards
Oskar
