### ISSUE TITLE
Fortnox API Library 3.4.0 installation

### ISSUE THREAD

**Issue by LennyHoglund** [FortnoxAB/csharp-api-sdk#112]
Hello Fortnox API provider, 

I have just installed Fortnox API Library 3.4.0 in my project developed using Microsoft Visual Studio 2019 Version 16.7.6.
After building the project I receive a couple of warnings, see enclosed document. I can run the project but I want to get rid of the warnings. Do you have a solution before I start with a lot of "plumbing" in order to get rid of the warnings? This is not a big issue, just to make you aware of the problem.

Thank you for your good work on the API from an pleased developer,
Lennart Hoglund 
[Document34.pdf](https://github.com/FortnoxAB/csharp-api-sdk/files/5390382/Document34.pdf)

**Comment by richardrandak** [comment]
Hello!
All the warnings seems to be connected to the Newtonsoft.Json dependency. The SDK is using version 12.0.3. It seems your solution is somewhere referencing this dependency also, but old version 6.*.*
I am not much experienced with dependency resolving. If you can update dependency in your solution to the same version I think the warnings will disappear.

**Comment by richardrandak** [comment]
Seems that this hint is relevant. From the warning it looks the old version of Newtonsoft.Json is referenced from MicrosoftSDK  / .NET SDK or something.. would be simpler to just reference NuGet if you are using it in the code. Updating it is then trivial.

Consider app.config remapping of assembly "Newtonsoft.Json, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" from Version "6.0.0.0" [C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\plugins\Diagnostics\Newtonsoft.Json.dll] to Version "12.0.0.0" [C:\Lewab Solutions\packages\Newtonsoft.Json.12.0.3\lib\net45\Newtonsoft.Json.dll] to solve conflict and get rid of warning

**Comment by richardrandak** [comment]
What other dependencies are you using in the project?  It can be the old Newtonsoft.Json is part of some other package. Then I don't know what can be done to resolve it.

**Comment by LennyHoglund** [comment]
Hello Richard,

Thank you for your quick responses. Yes, the issue is related to different versions of Newtonsoft.Json. I will fix that in my projects.
By the way, I like the new Fortnox API, it help us a lot in our integration with Fortnox.

Keep up the good works,


[cid:image001.png@01D6A3AF.E8633B70]
Lennart Hoglund
CEO & Senior System Architect

Lewab AB
Nytorgsgatan 24
116 22  Stockholm
Sweden
Phone    +46 (0) 8 641 3911
Mobile   +46 (0)70 646 1328
E-mail     lennart.hoglund@lewab.com<mailto:lennart.hoglund@lewab.com>
Site          www.lewab.com

**Comment by richardrandak** [comment]
Thank you, I am glad you like my work.
Please let me know in case you encounter any issues with the SDK.
