### ISSUE TITLE
SupplierInvoiceConnector has Cancel instead of Delete

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#113]
Hej,
Why all connectors have Delete() method and SupplierInvoiceConnector has Cancel instead ? :)

**Comment by richardrandak** [comment]
Because Delete is not the same as Cancel :)
Not all connectors has the delete method. Some Fortnox resources simply can not be deleted. The API offer action 'cancel' for invoices/offers/orders which marks them as cancelled. The resources are, however, still there and can be retrieved by Get method.

**Comment by bpaolo71** [comment]
Right. I have not thought about this. Thank you.
