### ISSUE TITLE
Contracts connector DocumentNumber on POST

### ISSUE THREAD

**Issue by jezloop** [FortnoxAB/csharp-api-sdk#115]
Hi!

I seem to get an empty string as DocumentNumber when creating a contract.
var contractResult = contractConnector.Create(contract);

contractConnector.HasError is false
and
contractConnector.DocumentNumber is empty.

Many thanks for a good API connector overall though!

**Comment by richardrandak** [comment]
Hello,
the `DocumentNumber` of the connector has nothing to do with created contract entity. The properties of a connector are used (for now) as search filter when calling `Find()` method
You should check the `contractResult` variable. That is the created contract and has `DocumentNumber` populated

**Comment by jezloop** [comment]
Sorry, idiot misstake from me :)
