### ISSUE TITLE
Actions for invoice

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#118]
Hi, is there support for actions for invoices. If I for example would like to send a invoice by email like this...

https://api.fortnox.se/3/invoices/1/email

Described in the documentation https://developer.fortnox.se/general/actions/

Is this possible through the SDK or should I create that request myself?

**Comment by richardrandak** [comment]
Hello!
Yes, the actions are implemented. Always check the connector for the resource. In your case, InvoiceConnector.
They don't have async version defined but it should be easy for you to do async wrapper for it.
Other issue is that the actions are not well tested. Please let me know if you find something not working.

**Comment by MagnusModig** [comment]
Got it, thanks
