### ISSUE TITLE
Throttle method in BaseClient is not threadsafe

### ISSUE THREAD

**Issue by anthonn** [FortnoxAB/csharp-api-sdk#119]
In BaseClient the RateLimiter for each accessToken is retrieved. But it looks like it is not threadsafe.
RateLimiter is a Dictionary and I think the code would throw an error if two threads pass by the if statement, checking if a key already exists, simultaneously. And then trying to add the same key twice.
Well it is very unlikely, but thought I should tell.

        private async Task Throttle()
        {
            if (string.IsNullOrEmpty(AccessToken))
                return;

            //Add ratelimiter for access token if does not exist
            if (!RateLimiters.ContainsKey(AccessToken))
                RateLimiters.Add(AccessToken, TimeLimiter.GetFromMaxCountByInterval(LimitPerSecond, TimeSpan.FromSeconds(1)));

            await RateLimiters[AccessToken];
        }

**Comment by richardrandak** [comment]
You are right, it was not implemented with focus on thread-safety, I assume there are more issues like this.
