### ISSUE TITLE
YourReference missing from Contract

### ISSUE THREAD

**Issue by jezloop** [FortnoxAB/csharp-api-sdk#121]
Hi

The Contract entity is missing YourReference, would it possible to add that?

Best regards
Oskar

**Comment by richardrandak** [comment]
Of course. I'll add it both master and beta branch

**Comment by jezloop** [comment]
Hi

Can you make a new release with nuget? 👍

**Comment by richardrandak** [comment]
I will make one more fix for and create nuget today

**Comment by richardrandak** [comment]
https://www.nuget.org/packages/Fortnox.NET.SDK/3.5.3
