### ISSUE TITLE
UseRateLimiter 

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#124]
What does bool UseRateLimiter affect in a search?

**Comment by richardrandak** [comment]
Every request (except retrieving access token by AuthorizationConnector) is throttled by rate limiter by default.
Find() method is normally a single request, unless you use unlimited page size, in which case the request is sent for each page of size 500 and aggregates the results automatically.

Is that answer to your question, or do you mean something else by "search"?

**Comment by MagnusModig** [comment]
I'm thinking about find a customer, when doing that I need to retrieve all customers from the api or be able to search directly based on parameter, but this code seem to use "LIKE" as parameter and not == 

            var customerConnector = new CustomerConnector
            {
                AccessToken = "xyxyxyx",
                ClientSecret = "xxx",
                UseRateLimiter = true,
                Search = new CustomerSearch { CustomerNumber = customerNumber }
            };

            var customers = customerConnector.Find();

// On the line below I can search by exact customernumber, but the above seem to use "LIKE"
result = customers.Entities.Any(x => x.CustomerNumber == customerNumber);

**Comment by richardrandak** [comment]
You are right. The search settings/parameters are executed as LIKE filter on server side. That is the API behavior and as far as I know, it can not be changed to equality comparison. If that is what you need, you have to filter it yourself after obtaining all customers.
