### ISSUE TITLE
Can't download invoice document

### ISSUE THREAD

**Issue by valiman** [FortnoxAB/csharp-api-sdk#126]
I sent a mail to support but they refered me to the git for some reason.

I am able to download a document through postman with actions print and preview but not through the SDK, even tried WebClient.

I cant give out our client-secret, user api or document number so im not sure how this case will be debugged ...

**Comment by richardrandak** [comment]
This SDK is not covered by Fortnox anymore. All issues (especially if it works through postman) should be reported here in git.
Which NuGet version are you using? I can check if it works for me.

**Comment by valiman** [comment]
Version 3.5.3
I can download pdfs in general, its a specific PDF that cant be downloaded. I am not sure how i would share more info for you to be able to get this pdf.

**Comment by valiman** [comment]
Asked customer to change PrintTemplate to "st", that solved the problem. (https://developer.fortnox.se/documentation/resources/print-templates/)
