### ISSUE TITLE
EnumMemberAttribute Value is ignored by DataContractJsonSerializer

### ISSUE THREAD

**Issue by JonasTOJWS** [FortnoxAB/csharp-api-sdk#129]
See background at: https://stackoverflow.com/questions/48820025/enummemberattribute-value-is-ignored-by-datacontractjsonserializer

This means that the present beta that includes the TaxReductionTypes doesn't send their string equvivalents but the enum numbers. (Same for houseworktypes etc.)

For some reason it seem to default back to the "RUT"-type.

**Comment by richardrandak** [comment]
Hello Jonas!
The SDK is using other json serializer which handles the enum correctly as a string. 

Was there something not working for you? I see a problem that server does not accept the new green houseworks types, for some reason, but I think they are serialized correctly.

**Comment by JonasTOJWS** [comment]
Thanks for quick response!

Ok, it was just a theory since the enum values shows as number in the c#-debugger as well (could the version of c# compiler matter?). T

hey also talked about a workaround using the Newton.Json package in the end of that thread). But I assume you have tested it OK so there must be another cause..

Anyways when I set the TaxReductionType to `TaxReductionType.ROT` it still comes over as "RUT". 
Also the housework types doesnt come over at all on the invoice-rows (I haven't tried with the new green types yet).

**Comment by richardrandak** [comment]
I am actually using the newton.json package for serializing/deserializing. I believe that is the commonly used library for this purpose and nobody should ever use the default datacontract serializer :D 

About the C# debugger, it shows me the enum as string as default. Naturally, enum is always a number in memory but debugger should show the enum name. Maybe there are some settings for debugger?

<img width="259" alt="Screenshot_149" src="https://user-images.githubusercontent.com/58220739/103543611-1ee4a680-4e9f-11eb-95c0-309b7175df5d.png">

About the ROT comes over as RUT, I don't have this behavior. Could you show me your code?
Don't use the TypeOfReduction property of TaxReduction object. That is obsolete according to the Fortnox news. The TaxReductionType should be defined on invoice object instead.

**Comment by JonasTOJWS** [comment]
Thanks for your reply. 

Ok, my wrong, it seems like the non runtime inspector shows the numerical value

![rut](https://user-images.githubusercontent.com/22516588/103629846-22306e80-4f41-11eb-81ee-2337645c031c.png)

but when running the code the debugger shows the actual values like you say..

I tried one invoice set to the ROT type and two workhours of the type HVAC (you can see the debugger info on images below)

![rot](https://user-images.githubusercontent.com/22516588/103629994-5310a380-4f41-11eb-97c5-d087db1208e2.png)
![typ](https://user-images.githubusercontent.com/22516588/103629984-4f7d1c80-4f41-11eb-870e-c78803f17bf1.png)


However this is what came over to FN:

![rutfn](https://user-images.githubusercontent.com/22516588/103630143-90753100-4f41-11eb-8199-e08f47f920f0.png)
![hustypfn](https://user-images.githubusercontent.com/22516588/103630157-9408b800-4f41-11eb-8df6-bf6bcc13ef47.png)

As you can see the ROT type came as "RUT"  and the houseworktype HVAC didn't appear on the rows.

I use the following libraries:

* Fortnox sdk (latest beta) version 4.0.1.0
* Newtonsoft Json version 12.0.0.0 (should be latest)
* Visual studio VS2017 with netstandard 2.0

Do you know of any logfeature or similar way to catch what is actually sent over the httpclient (the json)?

**Comment by richardrandak** [comment]
Sorry, but I can barely see the debugger windows and the values are unreadable. Maybe try some printscreen tool like Lightshot.

I will try creating a ROT invoice with HVAC and check how does it look in FN on my side.

About the logfeature, I removed the request/response state from connectors, so there is no way to see it. You would have to use an external http tracer tool. I am using [Fiddler ](https://www.telerik.com/fiddler) for testing. Maybe in future I could add some logging subscription to the SDK.

**Comment by richardrandak** [comment]
So, I found out, when I create ROT invoice, its fine in FN. However, after I attach a TaxReduction, it is set to RUT even when I don't use the (obsolete) type property. After that is created, the invoice is changed to RUT as well.. 
Either it is a bug or I don't understand how it should be used after the new changes in API. I will ask the Fortnox support about that. Add the ROT type to the TaxReduction object as well, in that way it will work.

**Comment by JonasTOJWS** [comment]
Thanks a lot! I removed the TypeOfReduction since it was marked as deprecated. I will try to add it again and hope it will work!

**Comment by JonasTOJWS** [comment]
Ok it worked as suggested. Thanks again. Good to investigate since the new type "green" will come next year. I close this issue since it is not a bug in your SDK.

**Comment by richardrandak** [comment]
Hi Jonas! I was making a test of the tax reductions to show to Fortnox support, but it seems it works well now! Even the green housework types, except one.
Give it a try (without using the TaxReduction's TypeOfReduction) property as you had originally
