### ISSUE TITLE
Can't find connector to create custom document(inboud/outbound)

### ISSUE THREAD

**Issue by khungersumit22** [FortnoxAB/csharp-api-sdk#130]
Hi

There is no connector to create an inbound/outbound document using SDK?

**Comment by richardrandak** [comment]
No. Endpoints of warehouse module were not implemented. Or do you mean something else?

**Comment by khungersumit22** [comment]
Yes, I was looking for the same warehouse modules (creating purchase_orders/Inbound documents) :)

**Comment by richardrandak** [comment]
A generic issue/task #133 was created for warehouse. I am closing this one
