### ISSUE TITLE
SIEConnector can only retrieve SIE file for current financial year

### ISSUE THREAD

**Issue by TimHonkalammi** [FortnoxAB/csharp-api-sdk#132]
The `SIEConnector.Get(...)` can only retrieve the SIE file for the current financial year. 
There is no way to specify how to retrieve it for a specific financial year &mdash; there should be a way.

The REST API has support for specifying the financial year via the `?financialyear=` parameter.
https://developer.fortnox.se/documentation/resources/sie/

**Comment by richardrandak** [comment]
You are right, I'll add the optional argument to GET method

**Comment by richardrandak** [comment]
Please. update NuGet package to v4.0.2 to get the feature

**Comment by TimHonkalammi** [comment]
Works nicely now! Thank you very much!

**Comment by richardrandak** [comment]
Perfect! Thank you for pointing this issue out and let me know if you find something similar :) I'll close this issue now
