### ISSUE TITLE
ImportPayment source missing 'file' as source

### ISSUE THREAD

**Issue by LukasLonnroth** [FortnoxAB/csharp-api-sdk#134]
Even though it is not mentioned in the API documentation (https://developer.fortnox.se/documentation/resources/invoice-payments/) the source can have the value 'file' ex.

````json
"InvoicePayments": [
        {
            "@url": "https://api.fortnox.se/3/invoicepayments/1",
            "Amount": 10000,
            "Booked": true,
            "Currency": "SEK",
            "CurrencyRate": 1,
            "CurrencyUnit": 1,
            "InvoiceNumber": 1,
            "Number": "1",
            "PaymentDate": "2021-02-17",
            "Source": "file"
        },
````

In that case the Find() method fails with the following:
````
25.02.2021 07:04 - Error converting value "file" to type 'System.Nullable`1[Fortnox.SDK.Entities.Source]'. Path 'InvoicePayments[6].Source', line 1, position 1688.
````

I'm guessing this issue could be fixed by adding 'file' as a value to FortnoxSDK/Entities.Shared/Source.cs

Kindest regards,
Lukas

**Comment by LukasLonnroth** [comment]
Will test this locally and open a pull request if that is alright

**Comment by LukasLonnroth** [comment]
#135 Issue resolved.

**Comment by richardrandak** [comment]
I will publish an updated NuGet today
