### ISSUE TITLE
Unable to filter by Label

### ISSUE THREAD

**Issue by thelalle** [FortnoxAB/csharp-api-sdk#136]
In previous version we´re able to filter by label.

ie.
connector.Label = "2";

but this option is missing from new class InvoiceSearch.

**Comment by richardrandak** [comment]
I see.. I'll fix that.
Which version did you actually use before?

**Comment by thelalle** [comment]
Old one, we were quite happy with it, but Fortnox changed something regarding sending of electronic invoices.
So we went from:
-    <PackageReference Include="Fortnox.NET.SDK" Version="3.1.1" />
+    <PackageReference Include="Fortnox.NET.SDK" Version="4.0.3" />

**Comment by richardrandak** [comment]
I hope you'll be happy with the new version too :) I had to make some architecture changes so I could sleep better in the night, sorry for the trouble :D 
Anyway, is the change of sending electronic invoices working in the new one? If not, please create an issue. The reality is that I do not receive information about API changes, so it is hard to keep the SDK aligned.

**Comment by thelalle** [comment]
New API seems much more nice since the types now are of the correct version..

Regarding filtering by LabelReference, maybe the InvoiceSearch.LabelReference should be of type long to match the id in the LabelReference class.

**Comment by richardrandak** [comment]
On the other hand, with label it can be confusing to know if the id or the actual value is expected. I think I added a comment there, but would be pretty clear if the type is long
