### ISSUE TITLE
Find orderrows

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#137]
Hi

Using this code does not return the deliveryadress, invoiceadress or orderrows. How do I retrieve that from the orderconnector?

                var searchSettings = new OrderSearch()
                {
                    //limit page size to 50
                    Limit = 50,

                    //select page
                    Page = 1, //by default

                    // sort
                    SortBy = Sort.By.Order.DocumentNumber,
                    SortOrder = Sort.Order.Descending,

                    // narrow by OrderNUmber
                    DocumentNumber = orderNumber
                };
                var orders = orderConnector.Find(searchSettings);
                o = orders.Entities.Single(x => x.DocumentNumber == orderId);

**Comment by thelalle** [comment]
The find methods return a subset, like InvoiceSubset or in your case OrderSubset.
Then you can use the OrderConnector to retrieve the full order entity.

**Comment by MagnusModig** [comment]
Ahh, yes I found it now....
     ` var completeOrder = orderConnector.Get(o.DocumentNumber);`
