### ISSUE TITLE
Mixed datatypes

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#139]
Hi, when fetching a order the VAT value of an article is type decimal but the same value when making a invoice is type long?

**Comment by richardrandak** [comment]
Yeah, the types were originally defined based on documentation. For some reason, in documentation one is marked as integer and one as float.. that's why. 
But both should be integers. The only values possible, as far as I know, are 0, 6, 12, 25.

**Comment by richardrandak** [comment]
So I was wrong.. it seems it is possible to add custom VAT percentage in the settings. Then it is possible to use the also decimal percentage. I will change the invoice row VAT data type to decimal to cover also this rare scenario

**Comment by MagnusModig** [comment]
Thanks Richard :)
