### ISSUE TITLE
ConnectionCredentials race condition

### ISSUE THREAD

**Issue by mikaelhagerbro** [FortnoxAB/csharp-api-sdk#14]
If this sdk is used in a multi user environment, like an ASP.NET IIS web application, we will have a race condition since the `static` properties in `ConnectionCredentials` is shared in the application domain.

So all user requests that triggers Fortnox communication, will replace the `AccessToken` property with their own token, so it is possible that user A ends up using user B's token.

**Comment by amaszorek** [comment]
I have the same problem, could anyone comment on this issue?

**Comment by amaszorek** [comment]
@mikaelhagerbro did You find solution for this issue or maybe someone responded to your comment?

Best regards.
Adriana

**Comment by mikaelhagerbro** [comment]
I haven't got any response but I think the [developer forum](https://developer.fortnox.se/) might be a better place to ask questions and discuss issues.

Our solution is that we have forked the repository for solving this and we have also made some minor changes so it fits better in our web application project.

Best wishes and good luck!

**Comment by davidulvmoen** [comment]
We will try to fix this in next release that is coming soon.
