### ISSUE TITLE
Voucher is part of SupplierInvoiceSubset in api reference but not in c# sdk

### ISSUE THREAD

**Issue by johanneslundsten** [FortnoxAB/csharp-api-sdk#143]
Hello, I'm to get connected vouchers from an Invoice

In the api ref i found that there is a list of vouchers in the list view of supplier invoice.
[https://developer.fortnox.se/documentation/resources/supplier-invoices/](url)

But I cannot find it in the sdk:
[https://github.com/FortnoxAB/csharp-api-sdk/blob/965ac84f6d6d990faeacc3023234153a510f1044/FortnoxSDK/Entities.Subsets/SupplierInvoiceSubset.cs](url)

Is this by design or is it missing?

Best Regards
Johannes

**Comment by richardrandak** [comment]
Hello Johannes! 
I assume it is a new property, but you are right.
I noticed it last week and actually added it just yesterday to the SDK as pre-release. You can check 4.0.5-alpha NuGet.
Let me know if that works for you.

The thing is, it seems little inconsistent and I am not sure how to make it clear in SDK to not confuse the consumers. For instance, if you do booking of an supplier invoice, the response does not contains the Vouchers field. Instead, it contains the VoucherNumber, VoucherSeries and VoucherYear properties, similarly as with (customer) Invoice.

**Comment by johanneslundsten** [comment]
Thank you for your quick response!
I'll check it out and come back to you in a few days

Regards
Johannes
