### ISSUE TITLE
ArchiveConnector UploadFile never returns

### ISSUE THREAD

**Issue by dannemanNov** [FortnoxAB/csharp-api-sdk#144]
Hello.

I don't know where the problem is but I try to upload a file to archive but the function never returns. It is executing but never ends, like a infinite loop. I can see in my account that the file is uploaded and exists in inbox.

Dim connector = FortnoxClient.[Get](Of Connectors.ArchiveConnector)()
Dim file = connector.UploadFile("c:\temp\testfil.pdf", "inbox_v")  <--- This never returns, infinite execution and no timeout

/Daniel

**Comment by richardrandak** [comment]
This seems like the issue #94 I have tried to solve multiple times. It is probably related to using sync methods, which are internally just awaiting async methods. It seems to always reappear again.
Try calling the async method and await it yourself and let me know if it solves the issue.

**Comment by dannemanNov** [comment]
Hi.

No luck with async version of the upload:

Dim fileTask = inboxConnector.UploadFileAsync("c:\testfile.pdf", content, "inbox_v").ConfigureAwait(False)
Dim file As Entities.ArchiveFile = Await fileTask

I am on ASP.NET and tried the ConfigureAwait(false).

Any idea what to try?

**Comment by dannemanNov** [comment]
I found a workaround that seems to work:

 Dim syncContext = SynchronizationContext.Current
            SynchronizationContext.SetSynchronizationContext(Nothing)
            Dim file = inboxConnector.UploadFile(journal.TypeStr & journal.Raknare & "_" & Class1.RensaAlltUtomNumbers(Now.ToString) & ".pdf", arr, "inbox_v")
            SynchronizationContext.SetSynchronizationContext(syncContext)

**Comment by richardrandak** [comment]
Hello! I tried a simple test with ASP.NET Core Web API (C# .NET 5) and it was working fine. 
Sorry, I have no idea what to try next and don't have time resources to investigate it deeper. I only assume the VB code should work the same way as with C#. Please let me know if you find out more information about the issue.

Here is the simplest test use case. Can you try something like this?

![Screenshot_72](https://user-images.githubusercontent.com/58220739/112815787-f5dc4800-9080-11eb-876b-9c184653df0f.png)
