### ISSUE TITLE
Invalid method for EInvoiceAsync

### ISSUE THREAD

**Issue by thelalle** [FortnoxAB/csharp-api-sdk#145]
According to documentation https://apps.fortnox.se/apidocs#operation/einvoice "Send an invoice as e-invoice"
the EInvoiceCall should weirdly be a [GET] and not a [PUT].

"Felaktig action på faktura (PUT)."

**Comment by richardrandak** [comment]
ah, seems like the new documentation was finally published! Yesterday :) 
There will be many issues like this, I will try to find some time to sync the SDK with the new documentation
