### ISSUE TITLE
Newtonsoft version issues

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#150]
Hi, I have added FortNox SDK version 4.0.6 to my application. I then updated Newtonsoft to version 13.01 and tried debug, this worked fine. I then deplyoed my app to production server where I got an error when starting the application telling me the NewtonSoft was the wrong version. I then downgraded to version 12.03 and uploaded the new application to the production server, I now could run the application without NewtonSoft version errors. But If I now try to run debug on my local development machine I get an error saying Newtonsoft is the wrong version?

Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

Note: I do not have Newtonsoft 12.0.0.0 installed, I have 12.03, there is not even a 12.0.0.0 version to select from in Nuget.

**Comment by richardrandak** [comment]
Hello Magnus! I am afraid I don't know how to help you.
The SDK v4.0.6 uses Newtonsoft 12.0.3. Have you tried to remove the /bin folder and build it again at your local environment?
No idea why it tries to load 12.0.0.0

**Comment by MagnusModig** [comment]
Hi Richard, I had to remove to completely and also remove the section in the app.config file that referenced the wrong version. I know now to be more careful and not updating Netwtonsoft unless its updated in the SDK, But this can be a little heads up to users to check what version being used in the SDK before updating.

**Comment by richardrandak** [comment]
Do you know what was the issue in this case? I can't believe that just using an different version in a NuGet can cause this.

**Comment by MagnusModig** [comment]
It was beacuse I updated to a newer version and I belive the Fortnox SDK was excpecting one version of Newtonsoft but I had updated to a newer version in my project. At least everything points to that.....

**Comment by richardrandak** [comment]
I just think it is a common scenario that a program "A" is using nuget "B" and "C", while the nuget "B" is using older version of nuget "C"... seems weird that it would cause trouble and won't be resolved by the package manager. I think I tried that in VisualStudio and it worked fine.

**Comment by niklaswulff** [comment]
@MagnusModig i had a similar issue and used binding redirects in my web.config to enforce all efforts to use Newtonsoft to use the same version that Fortnox SDK uses.

**Comment by vanillajonathan** [comment]
The project should migrate from Newtonsoft.Json to System.Text.Json #166
