### ISSUE TITLE
add order rows without VAT, price etc

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#158]
Hi, is it possible to add simple text to the order rows without VAT, Account number and costcenter?

**Comment by richardrandak** [comment]
Yes, you can specify an order row with only description. So you can get something like this in the end

![Screenshot_10](https://user-images.githubusercontent.com/58220739/124882412-a3d88600-dfd0-11eb-883a-71bb972b6eef.png)

**Comment by MagnusModig** [comment]
Thats weird, when I try to add a row only containing description and blank articlenumber I got this error: "Request failed: Kostnadsställe måste anges för konto"

**Comment by richardrandak** [comment]
Hi Magnus, I had to update my comment, in case you read my previous
Try to set the account to 0

**Comment by MagnusModig** [comment]
So I only need to set AccountNumber to 0? I dont have to set VAT and CostCenter?

**Comment by richardrandak** [comment]
Yeah, that worked for me

**Comment by MagnusModig** [comment]
Hi, I contacted Fortnox about this and according to them one should enter "API_BLANK" as AccountNumber if you only want to add a text row. Their API is allowing up to 4 digits or string "API_BLANK". Any other text generate a fault. But this SDK only allows integers to be entered in AccountNumber, so I cannot add that.

**Comment by richardrandak** [comment]
Hmm. that is the problem with API_BLANK.. to support that, all properties would have to be strings, which is unacceptable

**Comment by MagnusModig** [comment]
I agree, I also have no problem using 0 as long as it doesn't interfere in some way. They mentioned something about how things are "bokförda", if you pass an integer that row will be "bokförd". But this is just text and that should not be "bokfört"

**Comment by richardrandak** [comment]
I just tried to do the same through the GUI, and the account number is also 0 when left blank

**Comment by MagnusModig** [comment]
Great, did you have the chance to also try and add API_BLANK to see what is will be then?

**Comment by richardrandak** [comment]
Yeah, setting the AccountNumber to 0 gives the same response as setting API_BLANK, resulting in AccountNumber 0 in response

**Comment by MagnusModig** [comment]
Allright I will use 0 then. Thanks for the help! :)

**Comment by richardrandak** [comment]
You're welcome! I am closing the issue then.
