### ISSUE TITLE
Is SDK Modifiable ? ReadOnly Feild

### ISSUE THREAD

**Issue by ujjan** [FortnoxAB/csharp-api-sdk#160]
Hello, i have installed the sdk in my project, when creating an order the Total price of the order and other fields are read-only. i am wondering if i can somehow modify the properties and define them. Plus there are some fields i would like to be nullable because every order doesn't contain all the fields, so is there a way to make such properties nullable? 
![SDK](https://user-images.githubusercontent.com/11665437/128677603-18aa48f7-4ff5-4b93-b531-14b8d5dda284.PNG)

**Comment by richardrandak** [comment]
1) The read-only properties are server-calculated, so you don't need to change them. It would result in BadRequest anyway, most likely. 
2) Every property in the SDK entities is null-able. If not, please let me know where is it.

What are you trying to do? The Total and TotalVAT is calculated based on order rows by server.
