### ISSUE TITLE
new Customer Default objects are null

### ISSUE THREAD

**Issue by xpagedeveloper** [FortnoxAB/csharp-api-sdk#167]
When I create a new customer from scratch all property entries is null.

Like i.e DefaultDeliveryTypes & DefaultTemplates is this a bug or normal behaviour?

**Comment by richardrandak** [comment]
Hi @xpagedeveloper !

Do you mean the customer instance you created, or the one you get by calling Create method?

When you create the customer instance, all the undefined properties will be null, naturally.
When you call Create, it will give you populated instance from server.

```
            var customer = new Customer()
            {
                Name = "ABC"
            };

            var x = customer.DefaultTemplates; // null;

            customer = FortnoxClient.CustomerConnector.Create(customer);
            var y = customer.DefaultTemplates; // not null;
```

**Comment by xpagedeveloper** [comment]
Great, thanks.
