### ISSUE TITLE
Attendancy

### ISSUE THREAD

**Issue by abbekall** [FortnoxAB/csharp-api-sdk#173]
Hi
I just tried to get attendancy data for all employees. The problem is that I just get a small portion of data, no working time "Tid" and mostly causecode "OK0". 

Is this a known issue or is there a quick fix?

Thanks!

**Comment by richardrandak** [comment]
Hello! I am not familiar with the TID module... can you try getting the data you want by using Postman? I mean, if the data you expect are not available that way, then there is nothing I can do in SDK.

**Comment by abbekall** [comment]
Hi!
Thanks, are trying but stumple across, probably a simple miss from my side, this message just trying to grab some customers (xyz = my access-token)

curl -X "GET" "https://api.fortnox.se/3/Customers" 
-H "Authorization: Bearer xyz" 
-H "Content-Type: application/json" 
-H "Accept: application/json"

{"message":"unauthorized"}

what am I missing?

**Comment by xpagedeveloper** [comment]
Do you have the correct scope added?

**Comment by abbekall** [comment]
Hi,
I can access the customers with the same token when using the SDK

Mvh Albert Winter
(Från telefonen)

**Comment by abbekall** [comment]
Perfect, works like a charm. The problem still remains that I feel I get to few posts from attenadance. Cant seem to find most of the working time

**Comment by richardrandak** [comment]
Then I think you need to contact official Fortnox support. I don't have much knowledge of attendance endpoints to help you with this. It is possible these endpoints are limited. There was already an issue #151 where it seems the API does not cover all that is visible through the GUI portal.

**Comment by abbekall** [comment]
Yes, thanks for your help

Mvh Albert Winter
(Från telefonen)

**Comment by richardrandak** [comment]
You're welcome. Please let us know when you get some information regarding this issue.

**Comment by richardrandak** [comment]
Any update?

**Comment by abbekall** [comment]
Hi!
No, nothing more then that the consider the service to work correctly but that it provides the correct info. So most either a bug or, most likely, some that cannot be fetched from the api.

Mvh Albert Winter
(Från telefonen)

**Comment by richardrandak** [comment]
So there is nothing we can do.. once again :)

**Comment by abbekall** [comment]
Looks like it unfortuantly, but thank you for terrific help

Mvh Albert Winter
(Från telefonen)

**Comment by richardrandak** [comment]
I know this may be a stupid question.. but you know you can do pagination, right? By default there will be just 100 records.
The part of the response should tell you how many records there are in total.

**Comment by abbekall** [comment]
Yes I do:)

Mvh Albert Winter
(Från telefonen)
