### ISSUE TITLE
HttpUtility.UrlEncode in BaseRequest doesn't handle special characters

### ISSUE THREAD

**Issue by Axemaningrosso** [FortnoxAB/csharp-api-sdk#174]
It encodes space to + breaking our integration when there are articles with space in the ArticeleNumber(Very many years of data)

**Comment by richardrandak** [comment]
Weird.. space in an identificator? It is no longer to possible to create such ArticleNumber.
Anyway... so you would prefer '%20' instead of '+' right?

Can you call Find method and tell me what is in the Url property for that article? Just to confirm they are encoding it with '%20'.

**Comment by richardrandak** [comment]
I changed the URI handling in the base request.. the main difference is encoding the space as "%20" instead of "+". Let me know if that solves your issue.
