### ISSUE TITLE
Set Financial Year VoucherFileConnection

### ISSUE THREAD

**Issue by erda08de** [FortnoxAB/csharp-api-sdk#175]
Hello.

I have an odd issue. When connecting a Voucherfile to a Voucher the voucherfile is attached to a Voucher on a previous Financial Year. How do I set Financial Year when connecting VoucherFileConnection:

Dim item As New Entities.VoucherFileConnection
item.VoucherNumber = FortNoxVoucherNumber
item.VoucherSeries = FortNoxVoucherSeries
'item.VoucherYear = FortNoxFinancialYear
item.FileId = file.Id
Dim newFile = connector.Create(item)

item.VoucherYear is ReadOnly?

/Daniel

**Comment by erda08de** [comment]
I got a reply from a fortnox that it is possible to set VoucherYear by adding a financialyeardate in the querystring. Hos is that possible to solve via SDK?

Ex https://api.fortnox.se/3/voucherfileconnections/?financialyeardate=2020-01-01 där ni skickar in fösta datumet i räkenskapsåret.

**Comment by richardrandak** [comment]
Hi, it seems like the SDK does not support it. I will need to add the parameter to the Create method. 
Maybe also to the Update method

**Comment by erda08de** [comment]
Richard
How do I get access to the url via SDK?

Connector has ha HttpClient but I can't find the Url parameter?

/Daniel

**Comment by richardrandak** [comment]
No, you can't do it in the SDK. You can try it by Postman.
Nevermind, I will check it when fixing this issue. Is it urgent, or can you wait for next week?

**Comment by erda08de** [comment]
Hello.

It not urgent the issue is solved temporary by setting selected/default
financial year in the GUI.

Many thanks
/Daniel

tis 28 sep. 2021 kl. 19:07 skrev richardrandak ***@***.***>:

**Comment by richardrandak** [comment]
I added optional parameter to Create method for specifying financial year id. I will publish a new NuGet soon.
Also changed VoucherNumber and Year properties to long? to match the types with the other entities to avoid neccessary conversions
