### ISSUE TITLE
RowId property missing in InvoiceRow

### ISSUE THREAD

**Issue by johannesjonsson** [FortnoxAB/csharp-api-sdk#176]
The API has a property RowId in InvoiceRow under the resource Invoice, but the RowId isn't available in the SDK. Is there a reason for this? RowId looks like a unique identifier for the InvoiceRow and that would be useful.

**Comment by richardrandak** [comment]
Hello!
The RowID was added just recently (2021-09-08) - https://developer.fortnox.se/blog/updating-document-rows-using-rowid/
So, the only reason for it not being in the SDK is that I did not have time to investigate the impact of these changes and implement it for the SDK. :)

**Comment by johannesjonsson** [comment]
Fair enough!

I checked the blog earlier but obviously missed that.
Would be great to have RowID added when possible, thanks.
