### ISSUE TITLE
InvoiceFileConnector request failed

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#177]
Hi,
I get Request failed: Bad Request (400) when i try to connect a file to an order.
This is what i do:

`ArchiveFile file = _archiveConnector.UploadFile(filePath, StaticFolders.Orders);`
`order = _orderConnector.Create(order);`
`InvoiceFileConnection fileConnection = new InvoiceFileConnection()`
`                {`
`                    FileId = file.Id,`
`                    EntityId = order.DocumentNumber,`
`                    EntityType = EntityType.Order,`
`                };`
`_fileConnectionConnector.Create(fileConnection);`

File and order creation worked and i can found them in Fortnox.
Is InvoiceFileConnection set right ?

**Comment by richardrandak** [comment]
try `FileId = file.ArchiveFileId`

**Comment by richardrandak** [comment]
I know it is confusing, that's why I added a note for the `FileId `property as `ID of the file.  Use ArchiveFileId from Inbox/Archive endpoint in this field.` No idea why they have two different ids for a file.. probably some legacy thing for back-compatibility.

If I remember right, this is just for the InvoiceFileConnection.. the other file connections, like vouchers, work with the `file.Id`, not `file.ArchiveFileId`.

**Comment by bpaolo71** [comment]
Thanks Richard for your quick reply.
I changed file.Id with file.ArchiveFileId as you suggested but i get the same error Bad request.
I checked file.ArchiveFileId value and it is a valid guid.

**Comment by richardrandak** [comment]
Alright... is there some error message?
You can maybe try the request in postman to see the full response.

**Comment by bpaolo71** [comment]
i checked med Fiddler and i got this: {"id":"809bb597-f8e2-49fa-9f5d-f744ad85b77a","error":"missing_mandatory_field"}
 I was checking documentation and i cannot find InvoiceFileConnection in the new side https://apps.fortnox.se/apidocs#group/Fortnox but i can find in the old one https://developer.fortnox.se/documentation/resources/invoice-file-connections/
Strange !

**Comment by bpaolo71** [comment]
Now it is working ! I missed IncludeOnSend = false

**Comment by richardrandak** [comment]
Huh.. i would not guessed that is a mandatory field :) Anyway, glad you figured it out.

**Comment by bpaolo71** [comment]
Thanks Richard and congratulations for the good job you are doing with the SDK
