### ISSUE TITLE
Missing field

### ISSUE THREAD

**Issue by andersjerenvik** [FortnoxAB/csharp-api-sdk#198]
Employee - EmployedTo

Thanks:-)

**Comment by richardrandak** [comment]
I added some missing properties.

**Comment by andersjerenvik** [comment]
Perfect, thanks. When is the next release? 

Would be best if I could have it right now of course:-)

**Comment by richardrandak** [comment]
Here - https://www.nuget.org/packages/Fortnox.NET.SDK/4.2.3
