### ISSUE TITLE
Projecktnummer saknas i SupplierInvoice objektet

### ISSUE THREAD

**Issue by vinblad** [FortnoxAB/csharp-api-sdk#20]
På en leverantörsfaktura så finns det en uppgift för projekt. Detta saknas på entiteten SupplierInvoice.

/mvh Anders

**Comment by davidulvmoen** [comment]
You are correct, we will soon handle this.

**Comment by vinblad** [comment]
Thank your, I've created a fork (?) where I've corrected this and some other things.

**Comment by davidulvmoen** [comment]
Thanks for sharing your information :)

**Comment by davidulvmoen** [comment]
I am closing this as it will be part of another issue.
