### ISSUE TITLE
PriceConnector.FindAsync requires priceListId and articleId

### ISSUE THREAD

**Issue by cynkan** [FortnoxAB/csharp-api-sdk#205]
Hi,
First of all, I´m so happy for this great SDK. Awesome!

A question,
How can we retrieve **all prices** without having to enter a priceId or articleId?

Thanks for all help.

**Comment by richardrandak** [comment]
Hello! 
Thank you for your nice words. I am glad you like it. :) 

About the prices, it seems like that is not possible. At least, based on the documentation and my experiments. You can ask support. If you can get it by Postman, let me know and I will add it to the SDK.

**Comment by cynkan** [comment]
Hi Richard,

It works fine to get all by the API at https://api.fortnox.se/3/prices by Postman so perhaps you could add FindAllAsync or something.

We also need some other things related to warehouse and locations. Can we hire you a couple of hours for theese changes? 
Please PM me at cyril.porseland@joboffice.se if possible.

**Comment by richardrandak** [comment]
Oh, you are right, it really works! Not sure what I have tried yesterday then :D I will add it to the SDK right now.

About the collaboration, I will let you know soon, I just need to speak with my current employer at Softwerk, if they are fine with it.

**Comment by richardrandak** [comment]
I have published a new NuGet - https://www.nuget.org/packages/Fortnox.NET.SDK/4.2.5
A new Find method was added for PriceConnector, taking just the search parameters, similarly to a common Find method of other connectors.

Let me know if you run into any issues.

**Comment by cynkan** [comment]
Great (Y)
Huge thanks. I will test this out.

**Comment by cynkan** [comment]
Just to let you know, it works fine ;)
