### ISSUE TITLE
How to get supplier invoice preview pdf

### ISSUE THREAD

**Issue by hexl84** [FortnoxAB/csharp-api-sdk#21]
We want import fortnox customer invoice and supplier invoice into our website, we use C# API to get the invoices. we want view the invoice preview PDF. As the InvoiceSubset(return by invoiceConnector) don't provide pdf url, so we use invoiceConnector.Preview() to save the PDF at local. But when we import the supplier invoice PDF as customer invoice, it doesn't work. We use SupplierInvoiceFileConnectionConnector get supplier invoice file, then loop the files and save the file at local, but SupplierInvoiceFileConnectionConnector return nothing. Could you please help us get the supplier invoice preview PDF?
![image](https://cloud.githubusercontent.com/assets/9064979/19334655/19b40074-9130-11e6-9776-0981ad6d1609.png)

**Comment by davidulvmoen** [comment]
I cannot see this functionality in the main API, and therefore we cannot implement it. However, you should be able to somewhat create it manually from a supplier invoice if you really need it.

I am closing this, but please get back if you have further questions.
