### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by mikaellonner** [FortnoxAB/csharp-api-sdk#218]
Hello
I'm using this flow to get the tokens: https://github.com/FortnoxAB/csharp-api-sdk/wiki/FortnoxAuth

The problem I get is that I'm getting a CORS error when I try 
public async Task GetToken()
       {
            var fortnoxAuthClient = new FortnoxAuthClient();
            var authWorkflow = fortnoxAuthClient.StandardAuthWorkflow;

            var token = await authWorkflow.GetTokenAsync(this.AuthorizationCode, _clientid, _clientSecret, _redirectUri);

            if (token != null)
                this.Token = token;
        }

Error;
![bild](https://user-images.githubusercontent.com/40313681/145780207-c388243c-86af-4653-b803-2aaec236ee16.png)
...sorry for the swedish, but I think you get the idea at least.

What must I change?

**Comment by richardrandak** [comment]
Hello! I am not familiar with Blazor, so I am afraid I can't really help you. The CORS never been issue for my projects, since the token request was executed on backend, not by browser.

You can, however, inject your own HttpClient into the FortnoxAuthClient in order to play with the headers.

**Comment by mikaellonner** [comment]
Alright, I will try that.
Also just got reply from support that they do not support this through front end at the moment.

Will try to inject my own client.

**Comment by vanillajonathan** [comment]
@mikaellonner you can make the call from the Blazor backend if running Blazor with Blazor Server or Blazor hosted on ASP.NET Core. For security reasons you do not want to make that call using Blazor WebAssembly (on the client side).

**Comment by mikaellonner** [comment]
But if you are using OCID this shouldn’t be a problem.

 

If I look at the flow this should work exactly as current best practice.

 

If not...what are you recommending me to use and how?

 

//Mikael

**Comment by vanillajonathan** [comment]
Well the `GetTokenAsync` method requires the `clientId` and `clientSecret` parameters which you do not want store on the client.

I suggest you do the `GetTokenAsync` call from inside a Controller. So your Blazor WASM calls an action inside a controller and that action does the `GetTokenAsync` call.

**Comment by mikaellonner** [comment]
Ok, yes I understand.

 

I actually tried to use the SDK but I got CORS issues when I tried that.

 

I will not store anything i the Blazor WASM of course.

 

//Mikael

**Comment by vanillajonathan** [comment]
CORS issues is because you are trying to use the Fortnox SDK from the Blazor WASM, hence it runs in the browser, don't do that. Let the backend use the Fortnox SDK. Place the Fortnox code in a controller and host your Blazor WASM app on top of ASP.NET Core. When you create a new Blazor project you get to chose the hosting model.

**Comment by mikaellonner** [comment]
Ok, I'll try that

Med vänlig hälsning
Mikael Lönner
________________________________
