### ISSUE TITLE
InvoicePayment source missing 'finance' as source

### ISSUE THREAD

**Issue by LinusCenterstrom** [FortnoxAB/csharp-api-sdk#219]
similarly to https://github.com/FortnoxAB/csharp-api-sdk/issues/134 the also returns "finance" as a source but it's not documented.
This causes a crash since the value can not be converted to the source enum

**Comment by richardrandak** [comment]
Alright, I will add it to the enum. Do you know where this value originates from?

**Comment by LinusCenterstrom** [comment]
I do not, can dig into it a bit if you want me to

**Comment by richardrandak** [comment]
It is not critical, just curious.. 
Here, a new NuGet - https://www.nuget.org/packages/Fortnox.NET.SDK/4.2.7
