### ISSUE TITLE
Remove legacy static authorization

### ISSUE THREAD

**Issue by vanillajonathan** [FortnoxAB/csharp-api-sdk#221]
> 2021-12-09: End of life for the existing authorization flow with long-lived access tokens. All integrations must use the OAuth2 Authorization Code Flow with expiring access tokens.

https://developer.fortnox.se/blog/fortnox/

**Comment by richardrandak** [comment]
It was postponed to 2022-01-09 if I remember right. 

The only thing what will happen is that you can no longer get a new static access token, but you can still use existing ones. Therefore the SDK should support it. So, I can delete the StaticTokenAuthWorkflow but not the StaticTokenAuth(orization)

**Comment by xpagedeveloper** [comment]
> It was postponed to 2022-01-09.
> 
> The only thing what will happen is that you can no longer get a new static access token, but you can still use existing ones. Therefore the SDK should support it. So, I can delete the StaticTokenAuthWorkflow but not the StaticTokenAuth(orization)

The old way will work until that token expires Fortnox says that that is aprox 10 years

**Comment by richardrandak** [comment]
@xpagedeveloper - But the activation (getting a new long-term token) should not be possible anymore even for old apps, right?

**Comment by bpaolo71** [comment]
It is working for us :) We can still get a new long-term token.

**Comment by xpagedeveloper** [comment]
I know that Fortnox has keept it for some types of customers but officially it’s closed since 6/1 2022

**Comment by CyrilPorseland** [comment]
Same here, we can get new static access tokens and the lifetime of them is 10 years so let them be. Don´t remove anything from this excellent SDK 👍

**Comment by andreassandin** [comment]
Yes please keep it but i wonder why the StaticTokenAuthWorkflow does not have a Revoke function?
Strangely it exists in the StandardAuthWorkflow with the name RevokeLegacyTokenAsync.

**Comment by richardrandak** [comment]
In that moment I thought the old auth class will be removed but revoke old access token should still be available, so I put it to new workflow class. Now it make sense to put it to StaticTokenAuthWorkflow.
