### ISSUE TITLE
set Leveranssätt

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#226]
Hi

Just wanted to check... if I want to set an orders "Leveranssätt" found under "Leveransuppgifter" in Fortnox, is it property "WayOfDelivery" I then set? Like this for example...

            var retrievedOrder = orderConnector.Get(1);
            retrievedOrder.WayOfDelivery = "Schenker";
            orderConnector.Update(retrievedOrder);

What if I set something that doesnt exsits in Fortnox, will that just trigger an error or will it insert the new value. Can I get a list of the current "Leveransätt" found in Fortnox?

**Comment by richardrandak** [comment]
1) You can get the "Leveransätt" by a WayOfDeliveryConnector.
var connector = Client.WayOfDeliveryConnector;
var search = new WayOfDeliverySearch() { ... }
var collection = await connector.FindAsync(search);
var entities = collection.Entities;

2) I believe, the retrievedOrder.WayOfDelivery should be a Code of an existing WayOfDelivery, so most likely, using an unexistent will throw an error.

**Comment by MagnusModig** [comment]
Great, thanks!

**Comment by MagnusModig** [comment]
Hi, I tried to get the current ways of delivery with this filter..
`var search = new WayOfDeliverySearch() {Limit = 50, FilterBy = new Filter.WayOfDelivery()};`

I must be doing it wrong beacuse I dont get any results at all. Do I need to tweak the filter?

**Comment by richardrandak** [comment]
try just `await connector.FindAsync(null)` .. should give you the results, if there are any

**Comment by MagnusModig** [comment]
Not sure whats going on but when changing to that I get this error "Request failed: Har inte behörighet för scope."

**Comment by richardrandak** [comment]
If you have access to the app in fortnox developer portal, check if has the `Settings` permission/scope enabled

**Comment by MagnusModig** [comment]
Thats it, thanks!
