### ISSUE TITLE
get name of resposible person for customer

### ISSUE THREAD

**Issue by MagnusModig** [FortnoxAB/csharp-api-sdk#228]
Hi

Where can I get the responsible person for a customer (see image)? [https://imgur.com/a/AGADDxw](https://imgur.com/a/AGADDxw)

**Comment by richardrandak** [comment]
I don't know :)
You can ask the Fortnox support about it and let me know.. if there is some new property for customer model, I will add it.

**Comment by MagnusModig** [comment]
They said its not possible. Do you know if its possible to retrieve the "Vår referens" value found on the same image?

**Comment by richardrandak** [comment]
I believe that's `OurReference` property

**Comment by MagnusModig** [comment]
I checked the OrderConnecter, CustomerConnector and InvoiceConnector and search by either documentnumber or customernumber but OurReference isnt available there

**Comment by richardrandak** [comment]
The property won't be retrieved when you do search (FindAsync) only when you get the full customer/order/invoice entity

**Comment by MagnusModig** [comment]
Got it, thanks
