### ISSUE TITLE
DeliveryState and WarehouseReady to Order.

### ISSUE THREAD

**Issue by TeroMalmberg88** [FortnoxAB/csharp-api-sdk#235]
Fortnox has added these fields to the order model in the GET/PUT API. Could these be added to this project ASAP. These fields seems to indicate whether the order is ready for delivery or not. And this is very critical in deciding what orders to fulfill.

**Comment by richardrandak** [comment]
I tried to add it as part a result of #229 and got stopped by an issue with the DeliveryState, which would break the functionality for those who does not have warehouse enabled.
What I think I could do, is to add the properties but making DeliveryState read-only. Would that be enough for you, or do you need to set/update this property as well?

**Comment by TeroMalmberg88** [comment]
We need to set/update it as well.

**Comment by richardrandak** [comment]
I could think of some workaround to enable updating the property separately as an alternative to the common Update method

**Comment by richardrandak** [comment]
I have created a pre-release NuGet with the order properties as well as action to make the order "warehouse ready".
Please check it out - https://www.nuget.org/packages/Fortnox.NET.SDK/4.3.2-warehouse-rc

When creating `FortnoxClient`, set its property `WarehouseEnabled ` to `true`, which will enable changing the DeliveryState of the order. In other case, the property won't be serialized.

Let me know if you have any issues.

**Comment by TeroMalmberg88** [comment]
Quick test indicated that it works fine. Thank you.
