### ISSUE TITLE
TotalToPay on invoice

### ISSUE THREAD

**Issue by andersjerenvik** [FortnoxAB/csharp-api-sdk#244]
Hi,

It seems that TotalToPay on Invoice-object is missing?
Can you please add that or is it missing of a reason?

Best regards,

Anders

**Comment by richardrandak** [comment]
No reason.. it was probably added later.
What is the difference now between Balance and TotalToPay?

**Comment by richardrandak** [comment]
The missing property was added. Please update to v4.3.4
