### ISSUE TITLE
Voucher ReferenceType missing enum value 'RECEIPT'

### ISSUE THREAD

**Issue by aramB** [FortnoxAB/csharp-api-sdk#246]
We have recently seen this errors in our logs:
```
Error converting value "RECEIPT" to type 'System.Nullable`1[Fortnox.SDK.Entities.ReferenceType]'. Path 'Vouchers[25].ReferenceType', line 1, position 7798. Requested value 'RECEIPT' was not found. 
```
when calling: `VoucherConnector.FindAsync(searchSettings))`

We are suspecting that the API is sending this new undocumented value `RECEIPT` and it looks like the C# enum definition needs to be updated.

**Comment by richardrandak** [comment]
Ok, I will add it.

**Comment by aramB** [comment]
@richardrandak If it helps to get this fix out faster I can create a PR?

**Comment by richardrandak** [comment]
Next time, you can do PR, that will speed the things up, since I am not actively working with the repository anymore.
In this case, there will be a NuGet published in few minutes
