### ISSUE TITLE
EmploymentForm SVT missing in SDK 

### ISSUE THREAD

**Issue by sfiplanday** [FortnoxAB/csharp-api-sdk#270]
Hi Fortnox Team, 
our integration uses the SDK to sync employees. However, we are currently getting an error when employees use the employmenttype SVT in Fortnox. On the old API site, it is not listed (https://developer.fortnox.se/documentation/resources/employees/) but on the new site, it is listed as a value (https://apps.fortnox.se/apidocs#operation/list_EmployeesResource). Can this be checked and added to the SDK?

**Comment by richardrandak** [comment]
Hello! 
The SDK is not maintained by "Fortnox Team", it's just me now :) 
I will add the `SVT` to the enum.

**Comment by psiplandy** [comment]
@richardrandak when there will be a new release version of Nuget package with extended enum?

**Comment by richardrandak** [comment]
@psiplandy Now it is :)

**Comment by richardrandak** [comment]
I have added the SNK to TaxAllowance.. pleas try now.
