### ISSUE TITLE
Employee Creation returns Object cannot be Null

### ISSUE THREAD

**Issue by sfiplanday** [FortnoxAB/csharp-api-sdk#277]
Hi, 
we are currently getting an error when trying to create an employee and were wondering which field is behind this error message. The SDK returns the following error message "Värdet kan inte vara null. (ftgavtalid)". Is this any special feature. Translating it did not really help.

**Comment by sfiplanday** [comment]
@richardrandak could you please have a look?

**Comment by adamelfstrom** [comment]
@sfiplanday Hi, do you have the `PersonelType` set on the employee you are trying to create?

**Comment by sfiplanday** [comment]
I am checking this with the team. What is the difference "TJM" "ARB"?

**Comment by adamelfstrom** [comment]
ARB = Arbetare (Worker)
TJM =  Tjänsteman (Employee)

These two types have different salary agreements in Fortnox

**Comment by sfiplanday** [comment]
Thanks was this a recent change that this field is required. Previously we did not had to provide it. I can't find the change in the API release notes or SDK release notes.

**Comment by adamelfstrom** [comment]
https://www.fortnox.se/developer/blog/mandatory-fields-in-the-employee-api
In this blog post from May they do mention new mandatory fields, but not PersonelType specifically. I assume the change was made together with the mentioned fields.

**Comment by sfiplanday** [comment]
I can confirm that adding the field worked. Can this be added to release notes/description that it is a mandatory field now. Previously, it had the default value of "TJM", now it is required to be send.
