### ISSUE TITLE
Property or indexer 'VoucherRow.Description' cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by bartclement** [FortnoxAB/csharp-api-sdk#279]
According to Fortnox Support: "The Description of our Voucher endpoint is not Read-Only".
How can I assign a value to this property via the SDK?

**Comment by bartclement** [comment]
This is great, thanks for your fast response. When will this version 4.3.13 be pushed to NuGet?

**Comment by bartclement** [comment]
> Hi, sorry for closing your issue before the update was available! It should be live now on NuGet.

Thanks, I see it now. But I think another small change is needed: 

public string Description { get; private set; }

This 'private' should be removed from the set? Or we alternatively we need a class constructor to set the value?

**Comment by adamelfstrom** [comment]
You are correct, I only removed the decorator but never fixed the actual property. A fix will be published shortly.
