### ISSUE TITLE
DefaultDeliveryTypes is overridden when updating Customer

### ISSUE THREAD

**Issue by mikael-karlsson** [FortnoxAB/csharp-api-sdk#28]
When following the instructions [here](https://developer.fortnox.se/documentation/resources/customers/) for updating a Customer, the Customers DefaultDeliveryTypes are all set to EMAIL. 

[This](https://github.com/FortnoxAB/csharp-api-sdk/blob/master/FortnoxAPILibrary/Entities/Customer.cs#L930) seems to be the issue, with DefaultDeliveryTypes being set in the constructor for the Customer class. 

This clashes with the statement that only the properties that you provide will be updated.

**Comment by xeterixon** [comment]
Seems like a bug or an error in the documentation.
There seems to be a somewhat of a hack-ish way around, though.
If you, when updating the customer, set DefaultDeliveryTypes to null, the previous values seems to stick. Something like:
`var customer = new Customer{/*Add the properties to update*/, DefaultDeliveryTypes=null}`

You may notice that I used a fair amount of "seems" in the statements above. Take that as an indication that I didn't test it that much and setting a property that is allocated in the constructor to null "feels" wrong...

I guess that the safest way to do it is to fetch the existing customer, update what ever you want to update and send the object back.

**Comment by mikael-karlsson** [comment]
Thanks for the answer. I tested the things you suggest myself, and as far as I can tell, it works. Mainly, I wanted to highlight the issue, even though I am not sure about the best way to go about resolving it in a more permanent way.
