### ISSUE TITLE
Not availability of the VATCode key in the SDK

### ISSUE THREAD

**Issue by masrooj** [FortnoxAB/csharp-api-sdk#281]
The availability of the VATCode key in the SDK seems to be missing. Despite checking various branches and releases, there doesn't appear to be a version where the VATCode key is implemented. While the invoice retrieved through Postman includes the VATCode, the SDK doesn't seem to provide it.
Do you have any suggestions for resolving this issue?
Fortnox.NET.SDK 4.3.14

**Comment by adamelfstrom** [comment]
Hi @masrooj, I have merged your PR and the new version of the SDK should now be available on NuGet.
