### ISSUE TITLE
Missing AuthorizationCode in ConnectionCredentials class?

### ISSUE THREAD

**Issue by raphikdanish** [FortnoxAB/csharp-api-sdk#29]
Hi,

This is with reference to my correspondence with your support.

**Expected objects in ConnectionCredentials class:**

> AccessToken
> ClientSecret
> AuthorizationCode

Cannot find _AuthorizationCode_ object in the class.

**Comment by xeterixon** [comment]
Out of curiosity, why do you need/want the AuthorizationCode to be in the ConnectionCredentials class?
From what I can tell, correct me if I'm wrong, the authorization code is only used once to fetch the access token, using the AuthorizationConnector or some custom pipeline. 
After that, only the ClientSecret/AccessToken combination is used to identify the Fortnox account and your integration.
Or perhaps I'm missing something...

**Comment by raphikdanish** [comment]
When run following code, I get error: Ogiltig inloggning.

> ConnectionCredentials.AccessToken = "xx";  //here I use my access token
> ConnectionCredentials.ClientSecret = "xxxx";  //here I use my client scret
> CustomerConnector customerConnector = new CustomerConnector();
> Customer customer = customerConnector.Get("1");
> if (customerConnector.HasError)
> {
> Console.WriteLine(customerConnector.Error.Message);
> }

I got following response from your support:

Change the header:

> ConnectionCredentials.AccessToken = "xx";

to:

> ConnectionCredentials.AuthorizationCode = "xx";


But, there is no AuthorizationCode field in the class!

**Comment by xeterixon** [comment]
You must first authenticate you integration, as described here: [https://developer.fortnox.se/documentation/general/authentication/](https://developer.fortnox.se/documentation/general/authentication/)
From that step you should get an AccessToken, which is used for any subsequent communication with Fortnox. 

The AuthorizationCode is only used at that single time, so it makes no sense having it in the ConnectionCredentials class.

Just to clarify: AuthorizationCode and AccessToken are **not** the same thing.

If you **have** authenticated the integration and lost the AccessToken there no way to get it back, as far as I know. In that case you have to deactivate the integration, reactivate it again (to get a new AuthorizationCode) and do the authentication step again.
I have done that I number of times today, simply to see how to handle a deactivated integration in our system.

So the answer you got from the support seems a bit wrong (but don't quote me on that... )

**Comment by raphikdanish** [comment]
I added integration as shown in the video but I still get "ogiltig inloggning" error:

Is it possible if I can send you my complete code with AccessToken and ClientSecret to your private email and you check if all settings are set properly?

Many thanks :-)

**Comment by xeterixon** [comment]
I can create a private github-repo, invite you to it so you can push your code to it, if you like.
It will be a private repo so it will only be visible to you and me. 
Also just to clarify: I'm am by no means connected to Fortnox. I simply use their SDK (and sometimes change it...).

**Comment by raphikdanish** [comment]
That will be great! Please invite me!

**Comment by xeterixon** [comment]
Done!

**Comment by raphikdanish** [comment]
That's okay.. Have a look when you have time. Thanks :+1:
