### ISSUE TITLE
ModeOfPayment

### ISSUE THREAD

**Issue by raphikdanish** [FortnoxAB/csharp-api-sdk#30]
Hi!
How to set ModeOfPayment to an Invoice/InvoiceRow object?

Invoice invoice = new Invoice();
ModeOfPayment m = new ModeOfPayment();
m.Code = "BG";
m.AccountNumber = "1230"; //4 digit?

Moreover, according to following AccountNumber can only be of 4 digits. But Bankgiro and Plusgiro have 8  or 7 digits. Is it some other accountnr?

https://developer.fortnox.se/documentation/resources/modes-of-payments/

**Comment by tsfcode** [comment]
ModeOfPayment is used when booking a payment to an invoice. The account number is which account in your account-chart that should be connected to the mode of payment. For example bankgiro connected to account 1930 and plusgiro connected to account 1920.

**Comment by davidulvmoen** [comment]
I am closing this, as I believe above information is correct.
