### ISSUE TITLE
SupplierInvoice

### ISSUE THREAD

**Issue by raphikdanish** [FortnoxAB/csharp-api-sdk#31]
I want to create supplier invoices. Where can set more information such as Orgnr, supplier's account nr/BG/PG, objectnr, ordernr?

```
SupplierInvoiceConnector sic = new SupplierInvoiceConnector();
SupplierInvoice si = new SupplierInvoice();
si.InvoiceNumber = "101";
si.OCR = "1010120101";
si.InvoiceDate = "2017-05-25";
si.DueDate = "2017-06-25";

sic.Create(si);
```

**Comment by davidulvmoen** [comment]
I cannot see these kind of information in the main API. However, you should probably take a look at the Suppliers resource instead.
