### ISSUE TITLE
Target NETStandard

### ISSUE THREAD

**Issue by vforteli** [FortnoxAB/csharp-api-sdk#36]
Since this project has no external dependencies it would be quite easy to convert to target netstandard2.0 and net47 in a mixed configuration. The only thing missing in netstandard2.0 is the mimetype parser which needs a dependency, or code for the parser
https://github.com/vforteli/csharp-api-sdk

**Comment by davidulvmoen** [comment]
Thank you for information :) I dont think we are ready today, but something like this will happen for shure!
