### ISSUE TITLE
Missing properties in OrderRow

### ISSUE THREAD

**Issue by robindorbell** [FortnoxAB/csharp-api-sdk#37]
There seems to be missing properties on OrderRow. These are related to the newly added Warehouse feature.

Reference:
https://developer.fortnox.se/blog/new-attributes-and-action-on-orderinvoicesupplier-invoice-endpoint/

**Comment by davidulvmoen** [comment]
Thank you! Warehouse is on current roadmap and will go into next release, however we do not have a scheduled date yet.
