### ISSUE TITLE
Update Invoice created from Order

### ISSUE THREAD

**Issue by robsur** [FortnoxAB/csharp-api-sdk#40]
When updating an Invoice that has been created from an Order (setting NotCompleted to True) you get an error message saying "En eller flera rader har koppling till en order, det går därför inte att uppdatera raderna via API."
This can be done with a REST call but not with the SDK.

**Comment by davidulvmoen** [comment]
Thank you, I am not able to create an invoice from a locked order. Could you please provide detailed reproduction steps?

**Comment by robsur** [comment]
Start by creating an Order in Forntox. 
Save the Order and create an Invoice from the Order.
Now try to set NotCompleted to True on the created invoice with a API call using the SDK.

**Comment by davidulvmoen** [comment]
I had no issues on my attempt. Could you please provide actual SDK XML and your REST call?
