### ISSUE TITLE
Alla primitives är av typen sträng

### ISSUE THREAD

**Issue by martingust** [FortnoxAB/csharp-api-sdk#42]
Hej,

Är det någon speciell anledning att alla primitves på era entiteter är av typen sträng?

T ex: `StockQuantity` på `Article`: https://github.com/FortnoxAB/csharp-api-sdk/blob/master/FortnoxAPILibrary/Entities/Article.cs#L427

Här anser jag det mest logiska borde vara att låta `StockQuantity` vara av typen `int`?

Som utvecklare mot ert API hade det underlättat enormt att inte behöva casta om alla nummer och booleans till strängar - med avseende både tidsmässigt och felkänsligheten det medför.

/Martin

**Comment by mgefvert** [comment]
+1 från mig ... jag byggde mina egna dataklasser istället och gick rakt på JSON-datat.

**Comment by martingust** [comment]
Med facit i hand skulle jag gjort detsamma. 

Det är för mig bortom allt förstånd hur man har designat C#-klienten - det är som om man inte vill göra rätt.

**Comment by vforteli** [comment]
Känns som den är automatiskt genererad från något verktyg som inte riktigt förstår sej på .Net...
