### ISSUE TITLE
Skapande av tomma rader i en faktura orsakar problem

### ISSUE THREAD

**Issue by parsoderstrom** [FortnoxAB/csharp-api-sdk#44]
Nu skapas alla fakturor manuellt. De tre första raderna används för "header" information. Det går utmärkt och allt blir som det ska. Se bild 1.

I den applikation som jag utvecklar ska fakturor skapas automatiskt och se likadana ut som de manuellt skapade. Mitt problem är att jag inte kan skapa tomma rader.  Det som verkar vara problemet är att DiscountType sätts automatiskt till AMOUNT, se bild 2.  

DiscountType skickas också till Fortnox som enda parameter vid skapandet av en rad.

    <InvoiceRow>
      <DiscountType>AMOUNT</DiscountType>
    </InvoiceRow>

Det jag tror händer är att Konto, Moms och Ks sätts automatiskt till defaultvärden pga att DiscountType sätts till ett värde.  Se bild 3. 

Problemet uppstår när man bokför fakturan. Då skapas det en post på konto 3001 som är 0kr, se bild 4.

Min fråga är om någon vet hur jag kan fixa detta genom att fortfarande använda FortnoxAPILibrary, eller om det är omöjligt och jag måste använda en annan metod. 

___________________________________________________________________________
![manuellt skapad faktura](https://user-images.githubusercontent.com/35331187/37400565-9690c964-2785-11e8-8399-8b25791c8834.PNG)
Bild 1: Manuellt skapad faktura. 

__________________________________________________________________________
![discounttype problem](https://user-images.githubusercontent.com/35331187/37397449-e961d8e0-277b-11e8-8fac-12ce21cc068c.png)
Bild 2: Skapandet av tom rad.

_________________________________________________________________________
![fakturaunderlag med felaktig information](https://user-images.githubusercontent.com/35331187/37397663-77d04daa-277c-11e8-85df-c18f90f701ec.PNG)
Bild 3: Fakturaunderlag med felaktig information

_________________________________________________________________________
![huvudbok 3001](https://user-images.githubusercontent.com/35331187/37400325-e1b20cc4-2784-11e8-9c6d-371c321d0f65.PNG)
Bild 4: Huvudbok, konto 3001

**Comment by vforteli** [comment]
Vet inte om det även gäller SDKn (bytte precis från SDKn till REST apin) men hade lite liknande problem med tomma rader för benämningar över 50 tecken.
Med REST apin går det dock att skapa helt tomma rader genom att fylla i de här fälten till fixade värden:

```
 sendorder.Order.OrderRows.Add(new
                    {
                        Description = "Description",
                        AccountNumber = 0,
                        ArticleNumber = "",
                        Price = 0,
                        OrderedQuantity = 0,
                        DeliveredQuantity = 0,
                    });
```

**Comment by parsoderstrom** [comment]
Det är SDKn jag använder. Skulle gärna vilja slippa byta ut allt till REST nu. 

Jag satte AccountNumber till "0000" vilket löste problemet med Konto och Moms, de blev tomma. Lite konstigt att det gick när det inte finns ett 0000 konto definierat (vad jag kan se). 

Men kostnadsstället blir det konfigurerade värdet i kundens faktureringsuppgifter. 

Jag testade att i efterhand uppdatera Kostnadsstället. Satte det till null och tom sträng utan resultat. Jag kunde sätta det till 0 men då gick det inte att bokföra pga att kostnadsställe 0 inte finns. Se bild 1. 

Min lösning blir nu att leva med att kostnadsstället är satt på tomma rader. 

_________________________
![resultat](https://user-images.githubusercontent.com/35331187/37407612-607fbb5e-279a-11e8-8023-db8ce64a093e.PNG)
Bild 1: Kostnadsställe satt till 0. Funkade inte att bokföra. 

_________________________
![ks](https://user-images.githubusercontent.com/35331187/37409748-5e42c5ca-279f-11e8-9970-37b92fc29444.PNG)
Bild 2: Kostnadställe blir det värde som är definierat för kunden.

**Comment by vforteli** [comment]
Det fungerar att sätta kostnadsstället till null med REST apin tex såhär:
```
{
    "Order": {
        "CustomerNumber": "5",
        "CostCenter": "",
        "OrderRows": [
            {
                "AccountNumber": 0,
                "ArticleNumber": "",
                "CostCenter": null,
                "Description": "test",
                "OrderedQuantity": "0",
                "DeliveredQuantity": "0",
                "Price": 0
            }
        ]
    }
}
```

Problemet med SDKn är att den lämnar bort fält som är null när den serialiserar ordern till xml. Borde till exempel ha attributet [XmlElement(IsNullable = true)] på fältet för att få med det.

**Comment by parsoderstrom** [comment]
Tack för förklaringen. 

Som systemdesigner skaver det lite att alla implementationer som vi gjort hittills har använt SDKn och pga av en liten detalj måste kommande applikationer byta till REST. Det blir inte så stringent som jag vill ha det. Ingen stor grej men det kan vara bra att veta att SDKn har sina begränsningar.
