### ISSUE TITLE
dotnetcore standard 2.0 compatible

### ISSUE THREAD

**Issue by rippo** [FortnoxAB/csharp-api-sdk#45]
Do you have any plans in making this compile using dotnetcore standard 2.0?

Warning NU1701: Package 'Fortnox.NET.SDK 3.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

The calls I have made so far does work.

**Comment by martingust** [comment]
Any updates on this?

**Comment by mortb** [comment]
I guess that maybe we're better off using plain REST-api if tryng to use fortnox? Official API that target .NET 4.6.1 and last release was two years ago; c'mon you guys! Maybe switch to this library (which I guess is unofficial) https://github.com/annytab/a-fortnox-client ?

**Comment by dennisahlin** [comment]
I can suggest using https://github.com/Zwapgrid/fortnox-sdk. We are actively checking PRs and maintaining it.

**Comment by mortb** [comment]
@dennisahlin nice!
Seems a bit unfocused of Fortnox though, that they don't seem to be supporting their API

**Comment by richardrandak** [comment]
Solution was now updated to .Net Core 3.0

**Comment by elonmallin** [comment]
Will the project be depending on .NET Core now instead of .NET Framework? Or will it work on both (only depend on netstandard2.1)?

When will these changes make it into the NuGet package? The last update was 2017 but this repo seems to be quite actively developed.

**Comment by elonmallin** [comment]
Okey the `.csproj` states TargetFramework is `netcoreapp3.0` so I guess dependency moved from .NET Framework to .Net Core.

**Comment by richardrandak** [comment]
Hello, to answer your question, the target framework will be .NET Core 3.1 since it is the latest version with long-term support from micro-soft.
![Screenshot_70](https://user-images.githubusercontent.com/58220739/72721897-5c143380-3b7d-11ea-91e7-4fae7eccde22.png)

You can download the repository and build the library for yourself as a temporary solution. According to my information, the package should be officially released next month. I am sorry for the delay.

**Comment by richardrandak** [comment]
If you plan to build the latest libraries by yourself, I added some more commits today which can make the user experience little better. 

Also, downgrading project to .Net Core 2.1 shouldn't be too hard if you really need full compatibility with .NET Framework. Only problem can be some features of C# 8.0 I have already been using, but I tried it now and simply adding a C# version to the project file fixed the issue.

**Comment by elonmallin** [comment]
Okey, but targeting .NET Core makes it not work for .NET Framework projects anymore though. It would be super cool to just target `netstandard2.1` instead to allow it to work on both .NET Core and .NET Framework.

I had a quick look and it seems like the only thing that needs .NET Core atm is the [FileExtensionContentTypeProvider](https://github.com/dotnet/aspnetcore/blob/93030a8819ec1a36ad35f8b6e4093287af20652c/src/Middleware/StaticFiles/src/FileExtensionContentTypeProvider.cs) in the `Microsoft.AspnetCore.StaticFiles` lib.

Would it be possible to copy that file straight from the AspnetCore repo into your repo and allow both core and framework instead by targeting netstandard?

**Comment by richardrandak** [comment]
Thank you for the suggestions. I will have to think about this a little.
If I understand right, you are using an project targeting .NET Framework and want to reference this SDK from there?
I am sorry for mixing up the .NET Standard 2.1 and .NET Core 2.1 before.

**Comment by elonmallin** [comment]
Yes exactly, I have a .NET Framework project that use the latest version of the NuGet package right now. So this one won't be able to get any updates if .NET Core is required for the next NuGet.

And I have another project on .NET Core that will probably integrate Fortnox soon.

Would be cool to use this same NuGet for both projects.

**Comment by richardrandak** [comment]
OK, based on this compatibility [table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), using .Net Standard 2.0 should be fine for both .NET Framework (4.6.1+) and .NET Core (2.0+) users. 
Seems to me that the dependency "Microsoft.AspnetCore.StaticFiles" you mention is compatible with this standard.

Anyway, I will try to implement the necessary changes, if any.

**Comment by elonmallin** [comment]
Great =) `netstandard2.0` should work well for both Core and Framework apps.

I'm not sure about the `Microsoft.AspnetCore.StaticFiles` dependency. It has AspneCore in the name which lead me to believe it requires the target framework to be .NET Core. But maybe that's not the case. The `*.csproj` of `Microsoft.AspnetCore.StaticFiles` also uses `netstandard2.0` but it also has dependencies on a bunch of other libraries but I'm not fully sure how that works.

**Comment by richardrandak** [comment]
I understand this Aspnetcore.StaticFiles looks complex but it is really simple utility library, normally used within the AspnetCore, but this is only a tiny piece which I am using it only for mapping content-type to file extension. IT is .NET standard compatible.

Just to prove this, I just generated a NuGet from the project targeting .NET standard 2.0 and referenced it from a .NET Framework 4.7.2 console. It works fine without warnings. 

Conclusion: The next release will be therefore targeting .NET Standard 2.0 :)

**Comment by elonmallin** [comment]
Awesome! =)
