### ISSUE TITLE
"Kan inte logga in, access-token eller client-secret saknas."

### ISSUE THREAD

**Issue by kezoponk** [FortnoxAB/csharp-api-sdk#46]
Jag har fyllt i min Access-Token/at och min Client-Secret/cs där det är meningen.
Inuti UrlRequestBase.cs har jag lagt till i error medelandet att den ska skriva vad den uppfattar som min at och cs;
 `throw new Exception("Kunde inte tolka felmeddelandet från Fortnox API.\n\n" + text +"\n\n AT: "+accessToken+"/"+AccessToken +"\n\n CS: "+clientSecret+"/"+ClientSecret+"\n\n", ex.InnerException);` 
Så när jag kompilerar programmet så står det i error medelandet, att min at och cs är helt korrekt, så förstår inte varför api;n ger mig ett error

{"ErrorInformation":{"Error":1,"Message":"Kan inte logga in, access-token eller client-secret saknas.","Code":2000311}}

**Comment by richardrandak** [comment]
From my investigation, this error is returned not only if credentials are undefined, but also when they are not in valid format. Please check if your used credentials are correct
