### ISSUE TITLE
Search articles?

### ISSUE THREAD

**Issue by raymondarvidsson** [FortnoxAB/csharp-api-sdk#47]
For example: Search att articles where StockWarning > DisposableQuantity.

Cannot se any way to do this.

And when I get a list of all articles, the Property 'StockWarning' is missing...

**Comment by richardrandak** [comment]
The API itself does not support searching based on StockWarning, and does not provide it in the article list. To get the property, you need to request specific article.

See https://developer.fortnox.se/documentation/resources/articles/ for details.
