### ISSUE TITLE
Customer.Type=UNDEFINED orsakar problem

### ISSUE THREAD

**Issue by laurilubi-lime** [FortnoxAB/csharp-api-sdk#50]
Vi skickar kunder till Fortnox F3 API. Vid uppdatering vill vi inte att `Type` i Fortnox ändras, dvs vi vill skippa `Type`. Hur får man till det via SDK?

Har provat att sätta till `UNDEFINED`, men det ger fel i Fortnox.

**Comment by dennisahlin** [comment]
@laurilubi-lime Vi har löst den här buggen i vår fork [här](https://github.com/Zwapgrid/fortnox-sdk/commit/c3d1040a1856c29aad738232bbad3bffb5217001).

**Comment by laurilubi-lime** [comment]
Tack för info! Ja, det kanske börjar bli dags att byta ut deras SDK mot en fork.

**Comment by BagheeraBear** [comment]
> @laurilubi-lime Vi har löst det här problemet i vår fork [här](https://github.com/Zwapgrid/fortnox-sdk/commit/c3d1040a1856c29aad738232bbad3bffb5217001).

Hej! 

Fick ni det att fungera? Testar med er fork, men får ändå: Ogiltig kundtyp. 2001200

**Comment by dennisahlin** [comment]
Ändringen i vår fork gör att Type är nullable, så om man inte sätter Type när man skall köra en update så ändras inte den Type som redan finns på kunden i Fortnox. Vi har däremot märkt att även om man sätter Type = null, så kan man ändå få 2001200 om kunden redan har UNDEFINED som Type i Fortnox.

**Comment by laurilubi-lime** [comment]
Vi körde inte senaste versionen av SDK:et och upgrade eller byte till fork kunde inte prioriteras just nu. Vår lösning just nu går ut på att hämta Customer från SDK innan vi skriver tillbaka den och använder Type som vi fick av Fortnox. Ibland får vi UNDEFINED och det accepteras inte som input, då byter vi till Type=Company.

**Comment by BagheeraBear** [comment]
Jag ändrade från enum, till string, så går det att skicka uppdateringar av kunder utan att skicka med <Type>-Taggen alls, och det fungerar. Det bryter befintlig API-kod, men det känns inte som att det gör något eftersom den inte uppdateras direkt ofta.
