### ISSUE TITLE
Connector to NoxFinans

### ISSUE THREAD

**Issue by BagheeraBear** [FortnoxAB/csharp-api-sdk#52]
Hi! There is no Connector to Nox Finans in this API. Are you planning to make such a connector? If not, do you have a suggestion as to how to solve the problem? The only way I see now is to import the whole API and make our own version? It does not seem to be possible to make a new Class that extends EntityConnector, or FinancialYearBasedEntityConnector, as there are internal fields/classes involved, unless one makes a new version of the whole solution.

**Comment by LancashireDave** [comment]
Hi. I also would like to see NoxFinans adding to this API. Did you ever get an answer?

**Comment by BagheeraBear** [comment]
@LancashireDave  Hi, not yet. I rolled my own, if you are interested you can have it.

**Comment by LancashireDave** [comment]
Hi


thanks for the reply.

It would be great to see what you did.

If nothing else it will give me some guidance. :-)


Regards,

Dave Barratt
(CEO & Brewmaster)

Email : Dave@westcoastbryggeri.com<mailto:Dave@westcoastbryggeri.com>
Phone : +46 76 116 0044



________________________________
