### ISSUE TITLE
Connector to Salary Transactions

### ISSUE THREAD

**Issue by BagheeraBear** [FortnoxAB/csharp-api-sdk#53]
I also miss the Connector to Salary Transactions. (As well as Nox Finans). The solution for now is to import the whole API into my project, and make new classes as they are missing. But it seems a bit odd they are not in the Official API.

**Comment by dennisahlin** [comment]
@BagheeraBear We're working on adding a SalaryTransactionsConnector in our fork [here](https://github.com/Zwapgrid/csharp-api-sdk), it will probably be done in a few days.

**Comment by BagheeraBear** [comment]
@dennisahlin Brilliant, thank you very much for the answer and the tip!
