### ISSUE TITLE
Hämta filtrerad kundlista

### ISSUE THREAD

**Issue by nylchr** [FortnoxAB/csharp-api-sdk#60]
Kan man på något sätt begränsa vilka kunder man hämtar med Find() utöver det självklara att ange en property i connectorn? Jag vill kunna hämta alla kunder med TYPE==COMPANY och exkludera TYPE==PRIVATE men det går inte i connectorn

**Comment by dennisahlin** [comment]
Just type lär inte gå, iom att det inte stöds av API:t i sig enligt dokumentationen: https://developer.fortnox.se/documentation/resources/customers/

**Comment by richardrandak** [comment]
As @dennisahlin mentioned, searching based on Type is not supported by API
