### ISSUE TITLE
Full entity from connectors

### ISSUE THREAD

**Issue by PatrikSwe99** [FortnoxAB/csharp-api-sdk#68]
Hi,

This is the first time I'm trying to do a project in .net and C#, so please be patience with my question.

Can someone help me to get full entity from connectors?

![Entities](https://user-images.githubusercontent.com/59102646/71445948-c5d82380-271e-11ea-893c-c12f93912ba9.jpg)

**Comment by richardrandak** [comment]
You can get the full entity by calling `connector.Get(item.CustomerNumber)`

**Comment by PatrikSwe99** [comment]
Thank you so much.

I have a sandbox account.
Can you please tell me what I´m doing wrong with the code below. I get the following error message:

![Error](https://user-images.githubusercontent.com/59102646/71764759-469bda00-2eec-11ea-8b35-e0661e11265d.jpg)


            var konton = AccountConnector.Find();
            
            foreach (var item in konton.AccountSubset)
            {
                // please not that this is a subset and not a full customer entity
                // however you can always get the full entity from connector if needed

                var accountNumber = item.Number;
                var test = AccountConnector.Get(accountNumber);
                var vatCode = test.VATCode;
                Console.WriteLine(vatCode);
            }

**Comment by PatrikSwe99** [comment]
Did some tests with AccountConnector.Limit. Maximum is AccountConnector.Limit = 37;, after that i get the Error Message above. I guess I do something wrong in the loop, just don't know what.

**Comment by richardrandak** [comment]
The error says "Too many requests". There is a limit on server side for about 4 requests per second. This will be fixed in next release so that the SDK will automatically wait before sending other requests, but for now, you have to handle it yourself by some "thread.sleep" workaround. Waiting 250-350ms after each request should be safe.

**Comment by dennisahlin** [comment]
You have not error handling in your code. After each request you should add code something like this:
```
if (connector.HasError){
    Console.WriteLine(connector.Error.Message);
}
```
So your code would be something like:
```
var konton = AccountConnector.Find();
if (connector.HasError){
    Console.WriteLine(AccountConnector.Error.Message);
    return;
}

foreach (var item in konton.AccountSubset)
{
    // please note that this is a subset and not a full customer entity
    // however you can always get the full entity from connector if needed

    var accountNumber = item.Number;
    var account = AccountConnector.Get(accountNumber);
    if (connector.HasError){
        Console.WriteLine(connector.Error.Message);
        break;
    }
    var vatCode = account.VATCode;
    Console.WriteLine(vatCode);
}
```

But, seeing the error message in the console "429 Too Many Requests".

429 is the HTTP status code, more info here: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

You can read more about Fortnox rate limits here: https://developer.fortnox.se/documentation/general/regarding-fortnox-api-rate-limits/

**Comment by PatrikSwe99** [comment]
Thank you so much for your inputs. I will do the workaround and implement error handling. 

One more question: is It possible to narrow down the query when I use .find with other fields than the ones enabled in connector.subset? I wish I could narrow down the accounts that have a particular vatCode. Something like AccountConnector.Find(vatCode = ”MP1”)

**Comment by richardrandak** [comment]
You are welcome! The filtering/searching properties are restricted by the Fortnox API. Searching accounts by VAT code is not supported unfortunately. Only properties defined in connector are available (SRU property).  If you find a parameter which is defined in the official API as 'searchable' but the SDK does not support it, please contact me or create a merge request.

**Comment by PatrikSwe99** [comment]
Once again thanks for your support. Now I know the basics and the structure. Now the fun begins :)
