### ISSUE TITLE
Write to messages?

### ISSUE THREAD

**Issue by dennisahlin** [FortnoxAB/csharp-api-sdk#74]
Hi!
I cannot find anything in documentation of API or SDK about writing messages to users. Is this possible? If not, can it be made possible?

Scenario: We export some invoice to some other place, and on the way it's validated for some properties that are required by receiver, but not by Fortnox. When this happens we want to notify the user that the property needs to be fixed for us to be able to export it, "Hey, we could not export invoice number {x} to {receiver} becuase {property} is [missing|invalid]. Please correct this.". We could send an email, but it would be more user friendly to send the notification as a message in Fortnox.

![image](https://user-images.githubusercontent.com/1439413/74838867-3913a580-531c-11ea-91e7-6880e1d297d8.png)

**Comment by richardrandak** [comment]
Hello!
Sorry, the SDK can not support this since it is not part of the Fortnox API.
I can ask around, if there is any way to do it other than using the web GUI.

**Comment by richardrandak** [comment]
Sorry for the late response, but there is no available way to send the messages other than the GUI.

**Comment by dennisahlin** [comment]
Ok, thank you.
