### ISSUE TITLE
Using double as data type for money?

### ISSUE THREAD

**Issue by fredrikhaglund** [FortnoxAB/csharp-api-sdk#76]
Hi @richardrandak!

Thank you for maintaining the sdk.

I noticed you commit 4dc42abcbb489a3dfd0799dba201419b5109eb01 Fix types for entity properties, where you change a lot of properties from string to typed data. 

Is there any thought behind choosing **double** for all properties representing money? Usually a good practice is to use **decimal** as data type when a variable represents financial and monetary values because floats and doubles cannot accurately represent the base 10 multiples that we use for money. 

[Read more.](https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency/3730040#3730040)

**Comment by richardrandak** [comment]
Hello @fredrikhaglund 
Thanks for the comment. I agree, decimals would be more suitable for those properties. I generated the types based on API documentation which says "float". I don't really know what type exactly is used in the back-end, so maybe changing the type in SDK will not solve the problem after all.

Anyway, it is not feasible for me to check all the properties and decide if decimal or float/double should be used. I can update all doubles to decimals though.

**Comment by richardrandak** [comment]
Fixed in commit 8993479834ab61d80d13d3aea9c0c57a77805a02
