### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by Matorit-Thomas** [FortnoxAB/csharp-api-sdk#77]
I am in the early stages of integrating Fortnox with our project and ran into this issue on the first example I tried. 

```
ArticleConnector articleConnector = new ArticleConnector();
articleConnector.AccessToken = "********-****-****-****-***********";
articleConnector.ClientSecret = "*********";
Articles result = articleConnector.Find();
```

This would throw the exception: "The request was aborted: Could not create SSL/TLS secure channel"
I ran wireshark and noted that the handshake was attempted with TLSv1 whereas api.fortnox.se runs TLSv1.3. I managed to remedy this by simply retargeting the project to .NET 4.8 and adding the following line to UrlRequestBase.SetupRequest

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls13;`

Making it:

```
internal HttpWebRequest SetupRequest(string requestUriString, string method)
{
	Error = null;

	HttpWebRequest wr = (HttpWebRequest)HttpWebRequest.Create(requestUriString);
	wr.Headers.Add("access-token", this.AccessToken);
	wr.Headers.Add("client-secret", this.ClientSecret);
	wr.ContentType = "application/xml";
	wr.Accept = "application/xml";
	wr.Method = method;
	wr.Timeout = this.Timeout;
	ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls13;
	return wr;
}
```

I'm sure there's a better place for this, but it worked in my case.

**Comment by richardrandak** [comment]
Hej! Seems like Fortnox just recently changed the required TLS version to Tls12.
I will push a fix for this so you'll be able to specify the protocol you want to use. Otherwise, default protocol of the system will be used.
Just out of curiosity, you're original protocol was TLS1.. what OS do you use?

**Comment by richardrandak** [comment]
Also, from your example I see your SDK still uses XML content type. Is that source of the NuGet? I would recommend using the latest changes available on GitHub for now instead of the NuGet, since a lot of stuff was fixed, but NuGet was not updated for a long time.

**Comment by Matorit-Thomas** [comment]
This snippet is from the latest release here on github which is linked to here [https://developer.fortnox.se/sdk/net-sdk/download/](url)

Now that you mention it I checked and apparently my installation of VS2019 preselects .NET 3.5 when I create console projects, and that was the source of the issue. I made a new project in 4.6 and referenced the assebly that I hadn't poked in and that worked straight off the bat.
