### ISSUE TITLE
Rate limiter should delay work instead of blocking the thread

### ISSUE THREAD

**Issue by anderssonjohan** [FortnoxAB/csharp-api-sdk#79]
Please provide async methods and use Task.Delay instead of blocking the thread. 
https://github.com/FortnoxAB/csharp-api-sdk/blob/8993479834ab61d80d13d3aea9c0c57a77805a02/FortnoxAPILibrary/UrlRequestBase.cs#L132

..or allow the user to opt-out of the builtin rate limiter to provide its own rate limiter outside the library.

Example solution:
https://stackoverflow.com/a/17119288/2447296

**Comment by richardrandak** [comment]
Fix was released with the option to disable the rate limiter. Hope that will help you.
The issue regarding missing async methods will continue as #73
