### ISSUE TITLE
Price uses the wrong property price

### ISSUE THREAD

**Issue by PatrikFomin** [FortnoxAB/csharp-api-sdk#81]
The entity Price has a property called PriceValue which is incorrect as it should be just Price (same as the class name). Easy fix is to just name the jsonproperty.

```
[Entity(SingularName = "Price", PluralName = "Prices")]
public class Price 
{
...
   /// <remarks/>
   [JsonProperty("Price")] // <--- Correct name
   public string PriceValue { get; set; }
...
}
```

**Comment by richardrandak** [comment]
Thank you for reporting this issue. It will be fixed soon.
