### ISSUE TITLE
Entity Supplier

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#83]
Entity Supplier doesn't have VATType field.

**Comment by richardrandak** [comment]
Please try version from this release, which should have all entities synced with documentation.
https://github.com/FortnoxAB/csharp-api-sdk/releases/tag/3.2.0-beta

**Comment by bpaolo71** [comment]
Sorry but i cannot find VATType not even in that version

**Comment by richardrandak** [comment]
Here it is -> https://github.com/FortnoxAB/csharp-api-sdk/blob/Beta/FortnoxAPILibrary/Generated/Entities/Suppliers/Supplier.cs

I haven't delete the old entities, maybe that is confusing. However, the code is using the new ones.
Try the NuGet https://www.nuget.org/packages/Fortnox.NET.SDK/3.2.0-beta , the VatType for supplier is there.

**Comment by bpaolo71** [comment]
now it looks fine :) thank you !
