### ISSUE TITLE
Entity CostCenter property Active

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#85]
both CostCenter and CostCenterSubset have property Active as string instead of bool? like others entities

**Comment by richardrandak** [comment]
This should also be fixed if you switch to the beta version

**Comment by bpaolo71** [comment]
ok now i found the problem. I downloaded the source code (https://github.com/FortnoxAB/csharp-api-sdk/archive/3.2.0-beta.zip) instead of  nuget package and it seems they are not aligned!
However if i use nuget package Active is a bool?.

**Comment by richardrandak** [comment]
Yes, it is boolean there. They are aligned. 
I was also confused, but the only problem is that I forget to delete the old entities in Entities" folder. The new (used) entities are in Generated/Entities folder.

**Comment by richardrandak** [comment]
oh, now I remember when I created the release I accidentally chose the master branch, but i updated it 15 minutes later.. maybe you have downloaded it before I fixed it. Anyway, use the NuGet or re-download the release and let me know if its okay

**Comment by bpaolo71** [comment]
now it looks fine :) thank you !
