### ISSUE TITLE
The OrderNumber field is missing in the OrderSubset

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#87]
The OrderNumber field is missing in the OrderSubset. At least it was present in the previous release.

**Comment by richardrandak** [comment]
I tried to keep the naming synced with documentation in the beta release. There is no "OrderNumber" property. Instead, the order identifier is "DocumentNumber"

**Comment by richardrandak** [comment]
Oh, but maybe that is missing too. I will look into this

**Comment by bpaolo71** [comment]
Now it's working fine :)
