### ISSUE TITLE
Supplier connector and VATType

### ISSUE THREAD

**Issue by bpaolo71** [FortnoxAB/csharp-api-sdk#88]
supplier connector return "REVERSE" if supplier has 0% in VATType field.
SupplierVATType has 3 values REVERSE, NORMAL, UIF but in interface there are 25%, 12%, 6%, 0%, Unionsinternt förvärv, Omvänd betalningsskyldigheter

**Comment by richardrandak** [comment]
Alright, thanks for reporting the issue.
I see.. the documentation defined only REVERSE, NORMAL and UIF, which does not match with the GUI.
I will add those other values 25, 12, 6 and 0, but I will have to ask the integration support what does the "NORMAL" represents then.
