### ISSUE TITLE
Order row sum missing when inserting a article

### ISSUE THREAD

**Issue by magmo-work** [FortnoxAB/csharp-api-sdk#92]
When adding a article to the list of orderrows like this...

newOrder.OrderRows.Add(new OrderRow { ArticleNumber = "1", Description = "Bok", Price = (decimal?) 125.3, OrderedQuantity = 1, Unit = "st"});

There is no setter for the sum and when looking in Fortnox on that inserted row it has no sum for that order row.

**Comment by richardrandak** [comment]
Ok, the row sum ("Total" property) is read-only, so the server is populating that. From my experimentats, it seems you have to define "DeliveredQuantity" for the row. The total price is calculated from that. You pay only for delivered articles, does not matter how many were ordered :)

**Comment by magmo-work** [comment]
Yes, when adding "DeliveredQuantity" I do get the total for that row. Thanks!
