### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by magmo-work** [FortnoxAB/csharp-api-sdk#93]
Hi

What could be the cause of this error "System.AggregateException: 'One or more errors occurred, WebException: The request was aborted: Could not create SSL/TLS secure channel." I get this error when debugging in VS 2019. I created a simple console app targeting .Net Framework  4.8.

I use the latest version installed using nuget package manager: Install-Package Fortnox.NET.SDK -Version 3.3.0

I get it on this line "var customers = customerConnector.Find();"

**Comment by richardrandak** [comment]
The server accepts only TLS v1.2+
Try adding this line "ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;" in start of your application to check if it solves the issue. What Windows version are you using?

**Comment by magmo-work** [comment]
Yes, that solved the issue. Thanks! when I got this issue I tried on Windows Server 2008. I have also tried Windows 10 and Windows Server 2012/2019 and there it works fine.

**Comment by richardrandak** [comment]
Yes, I guess the older windows use the older protocols by default, so you have to explicitly set it to the TLS1.2 in code.
