### ISSUE TITLE
DefaultInvoiceDeliveryType.ELECTRONICINVOICE cannot be deserialized

### ISSUE THREAD

**Issue by sveinungh** [FortnoxAB/csharp-api-sdk#95]
As of 3.3.0 DefaultInvoiceDeliveryType is replaced with DefaultDeliveryType which doesn't contain ELECTRONICINVOICE. When i call CustomerConnector.Get(id) for a customer with this setting an exeption is thrown. Is this a bug? Should we convert the data somehow or how do we fix this problem?

**Comment by richardrandak** [comment]
Hello!
According to the [documentation](https://developer.fortnox.se/documentation/resources/customers/), there are only three types.
![Screenshot_41](https://user-images.githubusercontent.com/58220739/86137458-9949fd80-baed-11ea-81db-b73ac32aa1ff.png)

I can ask around if it is a mistake in the documentation. Meanwhile, I will add the ElectronicInvoice as obsolete type to fix your issue. Let me know in case of any other issues.

**Comment by richardrandak** [comment]
I just checked this in GUI and there are only two options:

- Printout (corresponds to PRINT) 
- Email (corresponds to EMAIL)

![Screenshot_43](https://user-images.githubusercontent.com/58220739/86139528-25f5bb00-baf0-11ea-99de-c46666b38137.png)

**Comment by sveinungh** [comment]
If you register electronic invoice (link from the customer card) for the customer then a third option is visible. 

Also that state was possible to set without actually setting up electronic invoicing in the old API.

ex.InnerException.Message
"An error occured while deserializing the response. Check ResponseContent."
ex.InnerException.InnerException.Message
"Requested value 'ELECTRONICINVOICE' was not found."

**Comment by richardrandak** [comment]
Alright, I added the option. Please try using updated NuGet - https://www.nuget.org/packages/Fortnox.NET.SDK/3.3.1

**Comment by sveinungh** [comment]
Works! Thanks for the promt resolution of the issue!
